- name: " nginx installation "
  ansible.builtin.package: 
    name: 
      - nginx
    state: present
  notify: "starting"

- name: removing previous nginx directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: using the ansible common role
  ansible.builtin.import_role:
    name: common
    tasks_from: usable

- name: copying the expense.conf file
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify: "restart"