# - name: " starting and enabling "
#   ansible.builtin.service:
#     name: nginx
#     state: started
#     enabled: yes


# - name: " restart nginx "
#   ansible.builtin.service: 
#     name: nginx
#     state: restarted


- name: starting
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: restart
  ansible.builtin.service: 
    name: nginx
    state: restarted
